/**
 * Canonical Contract 04 classification of each exported settings key by the
 * runtime owner and when the setting takes effect. The schema test compares
 * this inventory with SETTING_KEYS so it cannot drift silently.
 */
export const CONTRACT_04_CONSUMER_INVENTORY = {
  'Workflow admission — next workflow invocation': ['enable_agent_workflow'],
  'Root model selection and request construction — live-effect router or next request': [
    'agent.model',
    'agent.efficientModel',
    'agent.capableModel',
    'agent.smartModel',
    'agent.smartProvider',
    'agent.smartReasoningEffort',
    'agent.balancedModel',
    'agent.balancedProvider',
    'agent.balancedReasoningEffort',
    'agent.cheapModel',
    'agent.cheapProvider',
    'agent.cheapReasoningEffort',
    'agent.choreModel',
    'agent.choreProvider',
    'agent.reasoningEffort',
    'agent.temperature',
    'agent.provider',
    'agent.maxTurns',
    'agent.maxOutputTokens',
    'agent.maxStreamOutputChars',
    'agent.maxModelRequestDurationMs',
    'agent.retryAttempts',
    'agent.transport',
    'agent.maxParallelToolCalls',
    'agent.codex.websocketFirstFrameTimeoutMs',
    'agent.codex.websocketInterFrameTimeoutMs',
    'agent.useFlexServiceTier',
  ],
  'Run containment — next request/run': [
    'agent.runBudget.maxUsdMicros',
    'agent.runBudget.maxUnpricedTokens',
    'agent.runBudget.maxActiveTimeMs',
    'agent.runBudget.warningHeadroomUsdMicros',
    'agent.runBudget.warningHeadroomUnpricedTokens',
    'agent.runBudget.warningHeadroomActiveTimeMs',
    'agent.runBudget.softHeadroomUsdMicros',
    'agent.runBudget.softHeadroomUnpricedTokens',
    'agent.runBudget.softHeadroomActiveTimeMs',
    'agent.runBudget.turnBackstop',
    'agent.runBudget.extensionPercent',
    'agent.runBudget.maxParentExtensions',
    'agent.runBudget.identicalToolCallThreshold',
    'agent.runBudget.escalation',
  ],
  'Provider credentials/configuration — security-sensitive, next client/request': [
    'agent.openrouter.apiKey',
    'agent.openai.apiKey',
    'agent.openrouter.baseUrl',
    'agent.openrouter.referrer',
    'agent.openrouter.title',
  ],
  'Mentor consultation — next mentor run': [
    'agent.mentorModel',
    'agent.mentorProvider',
    'agent.mentorReasoningEffort',
    'agent.mentorSamples',
    'agent.mentorPool',
  ],
  'Context compaction — next request': [
    'agent.contextCompaction.enabled',
    'agent.contextCompaction.mode',
    'agent.contextCompaction.compactThreshold',
    'agent.contextCompaction.compactThresholdTokens',
  ],
  'Shell execution — next tool invocation': [
    'shell.timeout',
    'shell.backgroundTimeout',
    'shell.maxOutputLines',
    'shell.maxOutputChars',
    'shell.autoApproveMode',
    'shell.useRtkCompression',
  ],
  'Sandbox policy — next tool invocation': [
    'sandbox.enabled',
    'sandbox.readPolicy',
    'sandbox.allowReadExtra',
    'sandbox.dockerHostControlProjects',
    'sandbox.allowNetworking',
  ],
  'Non-interactive auto-approval — next approval decision': [
    'agent.autoApproveModel',
    'agent.autoApproveProvider',
    'agent.autoApproveReasoningEffort',
  ],
  'Subagent launch/retention — next child run or registry operation': [
    'agent.subagentExplorerModel',
    'agent.subagentExplorerProvider',
    'agent.subagentExplorerReasoningEffort',
    'agent.subagentWorkerModel',
    'agent.subagentWorkerProvider',
    'agent.subagentWorkerReasoningEffort',
    'agent.subagentResearcherModel',
    'agent.subagentResearcherProvider',
    'agent.subagentResearcherReasoningEffort',
    'agent.subagentLibrarianModel',
    'agent.subagentLibrarianProvider',
    'agent.subagentLibrarianReasoningEffort',
    'subagent.asyncSessionTtlMs',
    'subagent.asyncMessageCap',
  ],
  'Interactive presentation — UI-only/presentation state': ['ui.historySize', 'ui.pasteThreshold', 'ui.displayMode'],
  'Logging and process environment — live logger effect or startup-only process configuration': [
    'logging.logLevel',
    'logging.disableLogging',
    'logging.debugLogging',
    'logging.suppressConsoleOutput',
    'environment.nodeEnv',
  ],
  'Application composition and terminal notifications — live-effect router, UI, or next request': [
    'app.shellPath',
    'app.mentorMode',
    'app.liteMode',
    'app.planMode',
    'app.orchestratorMode',
    'app.notifications',
    'app.notificationsOnApproval',
    'app.notificationsOnComplete',
    'app.searchViaShell',
  ],
  'File-tool behavior — next edit invocation': [
    'tools.logFileOperations',
    'tools.enableEditHealing',
    'tools.editHealingModel',
    'tools.editHealingProvider',
    'debug.debugBashTool',
  ],
  'SSH transport — restart-only connection configuration': [
    'ssh.enabled',
    'ssh.host',
    'ssh.port',
    'ssh.username',
    'ssh.remoteDir',
  ],
  'Web search — next search or security-sensitive provider credential': [
    'webSearch.provider',
    'webSearch.tavily.apiKey',
    'webSearch.exa.apiKey',
  ],
  'Memory — next retrieval/injection or restart-only storage construction': [
    'memory.enabled',
    'memory.directory',
    'memory.contextBudgetChars',
    'memory.searchDefaultLimit',
    'memory.searchMaxLimit',
  ],
  'Public hooks — restart-only discovery or next emitted hook event': [
    'hooks.user.enabled',
    'hooks.project.enabled',
    'hooks.trustedProjectRoots',
    'hooks.includeUserText',
    'hooks.includeToolArguments',
    'hooks.includeToolResults',
    'hooks.timeoutMs',
  ],
  'Provider ordering — presentation-only catalog ordering': ['providerOrder'],
} as const;
