packages:
  - packages/*
  - web-client
allowBuilds:
  better-sqlite3: true
  cpu-features: true
  esbuild: true
  sharp: set this to true or false
  ssh2: true
minimumReleaseAgeExclude:
  - ink-prompt
  - '@qduc/web-fetch@0.1.4'
