import { mkdir, writeFile } from 'node:fs/promises';
import { join } from 'node:path';

export const HOOK_DECLARATION_SHIM_FILENAME = 'term2-hooks.d.ts';
export const HOOK_TSCONFIG_FILENAME = 'tsconfig.json';

export const HOOK_DECLARATION_SHIM_CONTENT = `/**
 * Type declarations for Term2 hooks.
 * Auto-generated by Term2 to support editor type resolution.
 */

declare module '@qduc/term2/hooks' {
  export type Term2HookSchemaVersion = 1;
  export type Term2SessionMode = 'interactive' | 'non-interactive';
  export type Term2Status = 'idle' | 'working' | 'waiting_for_user' | 'waiting_for_approval';
  export type Term2StatusChangeReason =
    | 'startup'
    | 'user_turn'
    | 'queued_turn'
    | 'approval_continuation'
    | 'turn_started'
    | 'turn_finished'
    | 'turn_failed'
    | 'tool_started'
    | 'tool_finished'
    | 'approval_requested'
    | 'approval_resolved'
    | 'ask_user'
    | 'reset'
    | 'undo'
    | 'provider_changed'
    | 'tool_retry'
    | 'shutdown';
  export type Term2TurnOrigin = 'user' | 'queued' | 'approval_continuation';
  export type Term2TurnTerminalKind = 'response' | 'approval_required' | 'stale' | 'failed';
  export type Term2ErrorCategory =
    | 'aborted'
    | 'approval_rejected'
    | 'authentication'
    | 'configuration'
    | 'network'
    | 'provider'
    | 'rate_limited'
    | 'tool'
    | 'unknown';
  export type Term2ApprovalKind = 'tool' | 'ask_user' | 'preflight' | 'other';
  export type Term2ProposedDecision = 'approve' | 'reject' | 'abort' | 'auto_approve';
  export type Term2ApprovalResolution = 'approved' | 'rejected' | 'aborted' | 'auto_approved';
  export type Term2ApprovalResolutionSource = 'user' | 'policy' | 'system';

  export type Term2SubagentScope = {
    readonly agentId: string;
    readonly role: string;
  };

  export type Term2HookScope = 'root' | { readonly subagent: Term2SubagentScope };
  export type Term2ToolOwnership = Term2HookScope;

  export interface HookEventBase<Name extends Term2HookEventName = Term2HookEventName> {
    readonly type: Name;
    readonly schemaVersion: Term2HookSchemaVersion;
    readonly eventId: string;
    readonly sessionId: string;
    readonly timestamp: number;
    readonly scope: Term2HookScope;
    readonly turnId?: string;
    readonly toolCallId?: string;
  }

  export interface SessionStartHookEvent extends HookEventBase<'session.start'> {
    readonly cwd: string;
    readonly mode: Term2SessionMode;
    readonly providerName: string;
    readonly modelName: string;
  }

  export interface SessionEndHookEvent extends HookEventBase<'session.end'> {
    readonly reason: 'normal' | 'fatal_error';
    readonly sessionDuration: number;
  }

  export interface StatusChangeHookEvent extends HookEventBase<'status.change'> {
    readonly previous: Term2Status;
    readonly current: Term2Status;
    readonly reason: Term2StatusChangeReason;
  }

  export interface TurnStartHookEvent extends HookEventBase<'turn.start'> {
    readonly origin: Term2TurnOrigin;
    readonly userText?: string;
  }

  export interface TurnEndHookEvent extends HookEventBase<'turn.end'> {
    readonly terminalKind: Term2TurnTerminalKind;
    readonly duration: number;
  }

  export interface TurnErrorHookEvent extends HookEventBase<'turn.error'> {
    readonly errorCategory: Term2ErrorCategory;
    readonly safeMessage: string;
    readonly recoverable: boolean;
  }

  export interface ToolBeforeHookEvent extends HookEventBase<'tool.before'> {
    readonly toolName: string;
    readonly normalizedArguments: unknown;
    readonly attempt: number;
    readonly ownership: Term2ToolOwnership;
  }

  export interface ToolAfterHookEvent extends HookEventBase<'tool.after'> {
    readonly toolName: string;
    readonly duration: number;
    readonly normalizedResultSummary: unknown;
  }

  export interface ToolErrorHookEvent extends HookEventBase<'tool.error'> {
    readonly toolName: string;
    readonly duration: number;
    readonly errorCategory: Term2ErrorCategory;
    readonly safeMessage: string;
    readonly convertedToModelResult: boolean;
  }

  export interface ApprovalRequestedHookEvent extends HookEventBase<'approval.requested'> {
    readonly toolName: string;
    readonly normalizedArguments: unknown;
    readonly approvalKind: Term2ApprovalKind;
    readonly proposedDecision: Term2ProposedDecision;
  }

  export interface ApprovalResolvedHookEvent extends HookEventBase<'approval.resolved'> {
    readonly resolution: Term2ApprovalResolution;
    readonly source: Term2ApprovalResolutionSource;
    readonly executionFollowed: boolean;
  }

  export type Term2HookEventMap = {
    readonly 'session.start': SessionStartHookEvent;
    readonly 'session.end': SessionEndHookEvent;
    readonly 'status.change': StatusChangeHookEvent;
    readonly 'turn.start': TurnStartHookEvent;
    readonly 'turn.end': TurnEndHookEvent;
    readonly 'turn.error': TurnErrorHookEvent;
    readonly 'tool.before': ToolBeforeHookEvent;
    readonly 'tool.after': ToolAfterHookEvent;
    readonly 'tool.error': ToolErrorHookEvent;
    readonly 'approval.requested': ApprovalRequestedHookEvent;
    readonly 'approval.resolved': ApprovalResolvedHookEvent;
  };

  export type Term2HookEventName = keyof Term2HookEventMap;

  export type Term2HookEvent<Name extends Term2HookEventName = Term2HookEventName> = Term2HookEventMap[Name];

  export type Term2HookCallback<Name extends Term2HookEventName> = (
    event: Term2HookEventMap[Name],
  ) => void | Promise<void>;

  export interface Term2Hooks {
    on<Name extends Term2HookEventName>(event: Name, callback: Term2HookCallback<Name>): () => void;
  }

  export type Term2HookRegistration = (hooks: Term2Hooks) => void | Promise<void>;
}
`;

export const HOOK_TSCONFIG_CONTENT = JSON.stringify(
  {
    compilerOptions: {
      target: 'ES2022',
      module: 'NodeNext',
      moduleResolution: 'NodeNext',
      strict: true,
      skipLibCheck: true,
      baseUrl: '.',
      paths: {
        '@qduc/term2/hooks': ['./term2-hooks.d.ts'],
      },
    },
    include: ['**/*'],
  },
  null,
  2,
);

export async function ensureHookEditorShim(hookRoot: string): Promise<void> {
  try {
    await mkdir(hookRoot, { recursive: true });
    await writeFile(join(hookRoot, HOOK_DECLARATION_SHIM_FILENAME), HOOK_DECLARATION_SHIM_CONTENT, 'utf8');
    await writeFile(join(hookRoot, HOOK_TSCONFIG_FILENAME), HOOK_TSCONFIG_CONTENT, 'utf8');
  } catch (error) {
    // Passive editor shim generation fails open if directory permissions restrict writing
    void error;
  }
}
