/**
 * Converts @earendil-works/pi-ai catalog data files into the vendored term2
 * catalog module (catalog.generated.ts). Kept as a pure module so the
 * normalization is unit-testable; scripts/update-model-catalog.ts drives it
 * against a pi-ai checkout.
 */

/** A model entry as it appears in a pi-ai provider data file. */
export interface PiCatalogModel {
  contextWindow?: number;
  maxTokens?: number;
  name?: string;
  /**
   * Per-million-token USD prices from pi-ai. `input` and `output` are
   * required for a model to be priced; `cacheRead`/`cacheWrite` are
   * optional extra dimensions.
   */
  cost?: {
    input?: number;
    output?: number;
    cacheRead?: number;
    cacheWrite?: number;
  };
}

/** A pi-ai provider data file: api type -> model id -> model entry. */
export type PiProviderData = Record<string, Record<string, PiCatalogModel>>;

/** pi-ai data file basename -> the term2 provider id it is vendored under. */
export const VENDORED_PI_PROVIDERS: ReadonlyArray<{ file: string; provider: string }> = [
  { file: 'openai', provider: 'openai' },
  { file: 'openai-codex', provider: 'codex' },
  { file: 'openrouter', provider: 'openrouter' },
  { file: 'anthropic', provider: 'anthropic' },
  { file: 'moonshotai', provider: 'moonshotai' },
];

export interface CatalogMeta {
  schemaVersion: number;
  generatedAt: string;
  source: string;
}

const HEADER = `// Generated by scripts/update-model-catalog.ts from @earendil-works/pi-ai data.
// Do not edit manually. Run \`pnpm catalog:update\` to regenerate.

`;

/**
 * Render the pricing fields for a catalog entry. An entry is priceable only
 * when pi-ai reports both input and output prices; cache dimensions are
 * emitted when present. Incomplete entries (e.g. output missing) are omitted
 * from pricing so the runtime fails closed rather than guessing.
 */
function renderPricingFields(entry: PiCatalogModel): string[] {
  const cost = entry.cost;
  if (!cost || typeof cost.input !== 'number' || typeof cost.output !== 'number') {
    return [];
  }
  const fields = [`inputPricePerMTok: ${cost.input}`, `outputPricePerMTok: ${cost.output}`];
  if (typeof cost.cacheRead === 'number') {
    fields.push(`cacheReadPricePerMTok: ${cost.cacheRead}`);
  }
  if (typeof cost.cacheWrite === 'number') {
    fields.push(`cacheWritePricePerMTok: ${cost.cacheWrite}`);
  }
  return fields;
}

function renderModel(modelId: string, entry: PiCatalogModel): string {
  const fields = [`contextWindow: ${entry.contextWindow}`];
  if (entry.maxTokens !== undefined) {
    fields.push(`maxTokens: ${entry.maxTokens}`);
  }
  fields.push(...renderPricingFields(entry));
  return `    '${modelId}': { ${fields.join(', ')} },`;
}

/**
 * Build the catalog.generated.ts source text from pi-ai provider data files
 * (keyed by file basename) plus catalog metadata. Entries without a positive
 * context window are skipped; model ids are sorted for stable diffs.
 */
export function generateCatalogSource(piData: Record<string, PiProviderData>, meta: CatalogMeta): string {
  const lines: string[] = [];
  lines.push(HEADER.trimEnd());
  lines.push(`export const CATALOG_META = {`);
  lines.push(`  schemaVersion: ${meta.schemaVersion},`);
  lines.push(`  generatedAt: '${meta.generatedAt}',`);
  lines.push(`  source: '${meta.source}',`);
  lines.push(`} as const;`);
  lines.push('');
  lines.push(`export interface GeneratedCatalogModel {`);
  lines.push(`  contextWindow: number;`);
  lines.push(`  maxTokens?: number;`);
  lines.push(`  inputPricePerMTok?: number;`);
  lines.push(`  outputPricePerMTok?: number;`);
  lines.push(`  cacheReadPricePerMTok?: number;`);
  lines.push(`  cacheWritePricePerMTok?: number;`);
  lines.push(`}`);
  lines.push('');
  lines.push(`export const MODEL_CATALOG = {`);

  for (const { file, provider } of VENDORED_PI_PROVIDERS) {
    const providerData = piData[file];
    if (!providerData) continue;

    const models = new Map<string, PiCatalogModel>();
    for (const apiType of Object.values(providerData)) {
      for (const [modelId, entry] of Object.entries(apiType)) {
        if (typeof entry.contextWindow === 'number' && entry.contextWindow > 0) {
          models.set(modelId, entry);
        }
      }
    }

    const sortedIds = [...models.keys()].sort();
    if (sortedIds.length === 0) continue;

    lines.push(`  ${provider}: {`);
    for (const modelId of sortedIds) {
      lines.push(renderModel(modelId, models.get(modelId)!));
    }
    lines.push(`  },`);
  }

  lines.push(`} as const satisfies Record<string, Record<string, GeneratedCatalogModel>>;`);
  lines.push('');
  return lines.join('\n');
}
