/**
 * Converts @earendil-works/pi-ai catalog data files into the vendored term2
 * catalog module (catalog.generated.ts). Kept as a pure module so the
 * normalization is unit-testable; scripts/update-model-catalog.ts drives it
 * against a pi-ai checkout.
 */

/** A model entry as it appears in a pi-ai provider data file. */
export interface PiCatalogModel {
  contextWindow?: number;
  maxTokens?: number;
  name?: string;
  /**
   * Per-million-token USD prices from pi-ai. `input` and `output` are
   * required for a model to be priced; `cacheRead`/`cacheWrite` are
   * optional extra dimensions.
   */
  cost?: {
    input?: number;
    output?: number;
    cacheRead?: number;
    cacheWrite?: number;
  };
}

/** A pi-ai provider data file: api type -> model id -> model entry. */
export type PiProviderData = Record<string, Record<string, PiCatalogModel>>;

/** pi-ai data file basename -> the term2 provider id it is vendored under. */
export const VENDORED_PI_PROVIDERS: ReadonlyArray<{ file: string; provider: string }> = [
  { file: 'openai', provider: 'openai' },
  { file: 'openai-codex', provider: 'codex' },
  { file: 'openrouter', provider: 'openrouter' },
  { file: 'anthropic', provider: 'anthropic' },
  { file: 'moonshotai', provider: 'moonshotai' },
];

export interface CatalogMeta {
  schemaVersion: number;
  generatedAt: string;
  source: string;
}

/**
 * pi-ai ships 4096 for Muse Spark output limits, but the model supports
 * 131072 (see d1ae6ad2). Keep the fix in the generator so `pnpm catalog:update`
 * stays durable across pi-ai bumps until upstream corrects the source.
 */
const MAX_TOKENS_OVERRIDES: Record<string, Record<string, number>> = {
  openrouter: {
    'meta/muse-spark-1.1': 131072,
    'meta/muse-spark-1.1-contributor': 131072,
    'meta/muse-spark-1.2': 131072,
    'meta/muse-spark-1.2-contributor': 131072,
  },
};

function applyCatalogFixups(provider: string, modelId: string, entry: PiCatalogModel): PiCatalogModel {
  const override = MAX_TOKENS_OVERRIDES[provider]?.[modelId];
  if (override === undefined) return entry;
  return { ...entry, maxTokens: override };
}

/**
 * Newer pi-ai data keys models as `<kind>:<id>` (`chat:gpt-5`,
 * `classifier:typesafe/jev-1.13`). term2 only drives chat models and looks
 * them up by bare id, so keep `chat` entries without the prefix and drop every
 * other kind. Unprefixed keys (older pi-ai data) pass through unchanged; the
 * kind segment is a bare word, so `vendor/model:variant` ids are not mistaken
 * for one.
 */
function chatModelId(rawId: string): string | undefined {
  const match = /^([a-z]+):(.+)$/.exec(rawId);
  if (!match) return rawId;
  return match[1] === 'chat' ? match[2] : undefined;
}

const HEADER = `// Generated by scripts/update-model-catalog.ts from @earendil-works/pi-ai data.
// Do not edit manually. Run \`pnpm catalog:update\` to regenerate.

`;

/** A zero rate is free; negative sentinels and nonfinite rates are unknown. */
function isValidRate(rate: number | undefined): rate is number {
  return typeof rate === 'number' && Number.isFinite(rate) && rate >= 0;
}

/**
 * Emit a price only when both required rates and every supplied cache rate
 * are valid. Reject pricing as a whole: dropping an invalid optional rate
 * would turn unknown cache pricing into the runtime's absent-rate zero.
 * Model metadata remains available even when pricing is unknown.
 */
function renderPricingFields(entry: PiCatalogModel): string[] {
  const cost = entry.cost;
  if (
    !cost ||
    !isValidRate(cost.input) ||
    !isValidRate(cost.output) ||
    (cost.cacheRead !== undefined && !isValidRate(cost.cacheRead)) ||
    (cost.cacheWrite !== undefined && !isValidRate(cost.cacheWrite))
  ) {
    return [];
  }
  const fields = [`inputPricePerMTok: ${cost.input}`, `outputPricePerMTok: ${cost.output}`];
  if (typeof cost.cacheRead === 'number') {
    fields.push(`cacheReadPricePerMTok: ${cost.cacheRead}`);
  }
  if (typeof cost.cacheWrite === 'number') {
    fields.push(`cacheWritePricePerMTok: ${cost.cacheWrite}`);
  }
  return fields;
}

function renderModel(modelId: string, entry: PiCatalogModel): string {
  const fields = [`contextWindow: ${entry.contextWindow}`];
  if (entry.maxTokens !== undefined) {
    fields.push(`maxTokens: ${entry.maxTokens}`);
  }
  fields.push(...renderPricingFields(entry));
  return `    '${modelId}': { ${fields.join(', ')} },`;
}

/**
 * Build the catalog.generated.ts source text from pi-ai provider data files
 * (keyed by file basename) plus catalog metadata. Entries without a positive
 * context window are skipped; model ids are sorted for stable diffs.
 */
export function generateCatalogSource(piData: Record<string, PiProviderData>, meta: CatalogMeta): string {
  const lines: string[] = [];
  lines.push(HEADER.trimEnd());
  lines.push(`export const CATALOG_META = {`);
  lines.push(`  schemaVersion: ${meta.schemaVersion},`);
  lines.push(`  generatedAt: '${meta.generatedAt}',`);
  lines.push(`  source: '${meta.source}',`);
  lines.push(`} as const;`);
  lines.push('');
  lines.push(`export interface GeneratedCatalogModel {`);
  lines.push(`  contextWindow: number;`);
  lines.push(`  maxTokens?: number;`);
  lines.push(`  inputPricePerMTok?: number;`);
  lines.push(`  outputPricePerMTok?: number;`);
  lines.push(`  cacheReadPricePerMTok?: number;`);
  lines.push(`  cacheWritePricePerMTok?: number;`);
  lines.push(`}`);
  lines.push('');
  lines.push(`export const MODEL_CATALOG = {`);

  for (const { file, provider } of VENDORED_PI_PROVIDERS) {
    const providerData = piData[file];
    if (!providerData) continue;

    const models = new Map<string, PiCatalogModel>();
    for (const apiType of Object.values(providerData)) {
      for (const [rawId, entry] of Object.entries(apiType)) {
        const modelId = chatModelId(rawId);
        if (modelId === undefined) continue;
        if (typeof entry.contextWindow === 'number' && entry.contextWindow > 0) {
          models.set(modelId, entry);
        }
      }
    }

    const sortedIds = [...models.keys()].sort();
    if (sortedIds.length === 0) continue;

    lines.push(`  ${provider}: {`);
    for (const modelId of sortedIds) {
      const entry = applyCatalogFixups(provider, modelId, models.get(modelId)!);
      lines.push(renderModel(modelId, entry));
    }
    lines.push(`  },`);
  }

  lines.push(`} as const satisfies Record<string, Record<string, GeneratedCatalogModel>>;`);
  lines.push('');
  return lines.join('\n');
}
