import { SETTING_KEYS } from '../services/settings/settings-service.js';
import { getAllSettingDescriptions } from '../services/settings/settings-ui-metadata.js';

export type SettingCompletionItem = {
  key: string;
  description?: string;
  currentValue?: string | number | boolean;
};

export type SettingsCategory = {
  id: string;
  label: string;
};

export const SETTINGS_CATEGORIES: SettingsCategory[] = [
  { id: 'models', label: 'Models' },
  { id: 'safety', label: 'Safety' },
  { id: 'tools', label: 'Tools' },
  { id: 'ui', label: 'UI' },
  { id: 'memory', label: 'Memory' },
  { id: 'hooks', label: 'Hooks' },
  { id: 'misc', label: 'Misc' },
];

export const SETTING_DESCRIPTIONS: Record<string, string> = getAllSettingDescriptions();

/**
 * Settings that should be hidden from the UI (not for security, but for UX/workflow)
 * - agent.provider: Can only be changed at the start of a new conversation via model menu
 * - agent.autoApproveProvider: Controlled via model/provider selection workflows, hide from the general settings list
 */
export const HIDDEN_SETTINGS = new Set<string>([
  SETTING_KEYS.AGENT_PROVIDER,
  SETTING_KEYS.AGENT_SMART_PROVIDER,
  SETTING_KEYS.AGENT_BALANCED_PROVIDER,
  SETTING_KEYS.AGENT_CHEAP_PROVIDER,
  SETTING_KEYS.AGENT_CHORE_PROVIDER,
  SETTING_KEYS.AGENT_EFFICIENT_MODEL,
  SETTING_KEYS.AGENT_CAPABLE_MODEL,
  SETTING_KEYS.AGENT_MENTOR_MODEL,
  SETTING_KEYS.AGENT_MENTOR_REASONING_EFFORT,
  SETTING_KEYS.AGENT_AUTO_APPROVE_PROVIDER,
  SETTING_KEYS.AGENT_AUTO_APPROVE_MODEL,
  SETTING_KEYS.AGENT_MENTOR_PROVIDER,
  SETTING_KEYS.TOOLS_EDIT_HEALING_MODEL,
  SETTING_KEYS.TOOLS_EDIT_HEALING_PROVIDER,
  SETTING_KEYS.PROVIDER_ORDER,
  SETTING_KEYS.LOGGING_DEBUG,
  SETTING_KEYS.LOGGING_SUPPRESS_CONSOLE,
  SETTING_KEYS.ENV_NODE_ENV,
  SETTING_KEYS.APP_SHELL_PATH,
  SETTING_KEYS.APP_MENTOR_MODE,
  SETTING_KEYS.APP_LITE_MODE,
  SETTING_KEYS.APP_PLAN_MODE,
  SETTING_KEYS.APP_ORCHESTRATOR_MODE,
  SETTING_KEYS.TOOLS_LOG_FILE_OPS,
  SETTING_KEYS.DEBUG_BASH_TOOL,
  SETTING_KEYS.SSH_ENABLED,
  SETTING_KEYS.SSH_HOST,
  SETTING_KEYS.SSH_PORT,
  SETTING_KEYS.SSH_USERNAME,
  SETTING_KEYS.SSH_REMOTE_DIR,
  SETTING_KEYS.AGENT_SUBAGENT_EXPLORER_PROVIDER,
  SETTING_KEYS.AGENT_SUBAGENT_EXPLORER_MODEL,
  SETTING_KEYS.AGENT_SUBAGENT_EXPLORER_REASONING_EFFORT,
  SETTING_KEYS.AGENT_SUBAGENT_WORKER_PROVIDER,
  SETTING_KEYS.AGENT_SUBAGENT_WORKER_MODEL,
  SETTING_KEYS.AGENT_SUBAGENT_WORKER_REASONING_EFFORT,
  SETTING_KEYS.AGENT_SUBAGENT_LIBRARIAN_PROVIDER,
  SETTING_KEYS.AGENT_SUBAGENT_LIBRARIAN_MODEL,
  SETTING_KEYS.AGENT_SUBAGENT_LIBRARIAN_REASONING_EFFORT,
  SETTING_KEYS.SANDBOX_ALLOW_READ_EXTRA,
]);

export const COMMON_SETTINGS: string[] = [
  SETTING_KEYS.AGENT_MODEL,
  SETTING_KEYS.AGENT_REASONING_EFFORT,
  SETTING_KEYS.AGENT_TEMPERATURE,
];

export const CATEGORY_KEYS = {
  models: new Set<string>([
    SETTING_KEYS.AGENT_MODEL,
    SETTING_KEYS.AGENT_FAVORITE_MODELS,
    SETTING_KEYS.AGENT_MODEL_NICKNAMES,
    SETTING_KEYS.AGENT_SMART_MODEL,
    SETTING_KEYS.AGENT_SMART_REASONING_EFFORT,
    SETTING_KEYS.AGENT_BALANCED_MODEL,
    SETTING_KEYS.AGENT_BALANCED_REASONING_EFFORT,
    SETTING_KEYS.AGENT_CHEAP_MODEL,
    SETTING_KEYS.AGENT_CHEAP_REASONING_EFFORT,
    SETTING_KEYS.AGENT_CHORE_MODEL,
    SETTING_KEYS.AGENT_REASONING_EFFORT,
    SETTING_KEYS.AGENT_TEMPERATURE,
    SETTING_KEYS.AGENT_MENTOR_SAMPLES,
    SETTING_KEYS.AGENT_MENTOR_POOL,
    SETTING_KEYS.AGENT_USE_FLEX_SERVICE_TIER,
    SETTING_KEYS.AGENT_CONTEXT_COMPACTION_ENABLED,
    SETTING_KEYS.AGENT_CONTEXT_COMPACTION_MODE,
    SETTING_KEYS.AGENT_CONTEXT_COMPACTION_COMPACT_THRESHOLD,
    SETTING_KEYS.AGENT_CONTEXT_COMPACTION_COMPACT_THRESHOLD_TOKENS,
    SETTING_KEYS.AGENT_SESSION_ROLLOVER_ENABLED,
    SETTING_KEYS.AGENT_SESSION_ROLLOVER_MILESTONES,
    SETTING_KEYS.AGENT_SESSION_ROLLOVER_AUTO_BRIEF,
  ]),
  safety: new Set<string>([
    SETTING_KEYS.AGENT_MAX_OUTPUT_TOKENS,
    SETTING_KEYS.AGENT_MAX_STREAM_OUTPUT_CHARS,
    SETTING_KEYS.AGENT_MAX_MODEL_REQUEST_DURATION_MS,
    SETTING_KEYS.AGENT_MAX_MODEL_STREAM_IDLE_MS,
    SETTING_KEYS.AGENT_RUN_BUDGET_MAX_USD_MICROS,
    SETTING_KEYS.AGENT_RUN_BUDGET_MAX_UNPRICED_TOKENS,
    SETTING_KEYS.AGENT_RUN_BUDGET_MAX_ACTIVE_TIME_MS,
    SETTING_KEYS.AGENT_RUN_BUDGET_WARNING_HEADROOM_USD_MICROS,
    SETTING_KEYS.AGENT_RUN_BUDGET_WARNING_HEADROOM_UNPRICED_TOKENS,
    SETTING_KEYS.AGENT_RUN_BUDGET_WARNING_HEADROOM_ACTIVE_TIME_MS,
    SETTING_KEYS.AGENT_RUN_BUDGET_SOFT_HEADROOM_USD_MICROS,
    SETTING_KEYS.AGENT_RUN_BUDGET_SOFT_HEADROOM_UNPRICED_TOKENS,
    SETTING_KEYS.AGENT_RUN_BUDGET_SOFT_HEADROOM_ACTIVE_TIME_MS,
    SETTING_KEYS.AGENT_RUN_BUDGET_TURN_BACKSTOP,
    SETTING_KEYS.AGENT_RUN_BUDGET_EXTENSION_PERCENT,
    SETTING_KEYS.AGENT_RUN_BUDGET_MAX_PARENT_EXTENSIONS,
    SETTING_KEYS.AGENT_RUN_BUDGET_IDENTICAL_TOOL_CALL_THRESHOLD,
    SETTING_KEYS.AGENT_RUN_BUDGET_ESCALATION,
    SETTING_KEYS.AGENT_BACKGROUND_CHECK_IN_ENABLED,
    SETTING_KEYS.AGENT_BACKGROUND_CHECK_IN_INTERVAL_MS,
    SETTING_KEYS.SHELL_AUTO_APPROVE_MODE,
    SETTING_KEYS.AGENT_AUTO_APPROVE_REASONING_EFFORT,
    SETTING_KEYS.SANDBOX_ENABLED,
    SETTING_KEYS.SANDBOX_READ_POLICY,
    SETTING_KEYS.SANDBOX_DOCKER_HOST_CONTROL_PROJECTS,
    SETTING_KEYS.SANDBOX_ALLOW_NETWORKING,
  ]),
  tools: new Set<string>([
    SETTING_KEYS.ENABLE_AGENT_WORKFLOW,
    SETTING_KEYS.SHELL_TIMEOUT,
    SETTING_KEYS.SHELL_BACKGROUND_TIMEOUT,
    SETTING_KEYS.SHELL_MAX_OUTPUT_LINES,
    SETTING_KEYS.SHELL_MAX_OUTPUT_CHARS,
    SETTING_KEYS.SHELL_USE_RTK_COMPRESSION,
    SETTING_KEYS.WEB_SEARCH_PROVIDER,
    SETTING_KEYS.WEB_SEARCH_TAVILY_API_KEY,
    SETTING_KEYS.WEB_SEARCH_EXA_API_KEY,
    SETTING_KEYS.APP_SEARCH_VIA_SHELL,
    SETTING_KEYS.TOOLS_ENABLE_EDIT_HEALING,
    SETTING_KEYS.SUBAGENT_ASYNC_SESSION_TTL_MS,
    SETTING_KEYS.SUBAGENT_ASYNC_MESSAGE_CAP,
    SETTING_KEYS.TOOLS_SHELL_ENABLED,
    SETTING_KEYS.TOOLS_WEB_ENABLED,
    SETTING_KEYS.TOOLS_FILE_READ_ENABLED,
    SETTING_KEYS.TOOLS_FILE_WRITE_ENABLED,
    SETTING_KEYS.TOOLS_MEMORY_ENABLED,
    SETTING_KEYS.TOOLS_SESSIONS_ENABLED,
    SETTING_KEYS.TOOLS_SKILLS_ENABLED,
    SETTING_KEYS.TOOLS_MENTOR_ENABLED,
    SETTING_KEYS.TOOLS_SUBAGENTS_ENABLED,
    SETTING_KEYS.TOOLS_BACKGROUND_TASKS_ENABLED,
    SETTING_KEYS.TOOLS_USER_INTERACTION_ENABLED,
    SETTING_KEYS.TOOLS_CODE_CONTEXT_ENABLED,
  ]),
  ui: new Set<string>([
    SETTING_KEYS.UI_HISTORY_SIZE,
    SETTING_KEYS.UI_PASTE_THRESHOLD,
    SETTING_KEYS.UI_DISPLAY_MODE,
    SETTING_KEYS.LOGGING_LOG_LEVEL,
    SETTING_KEYS.LOGGING_DISABLE,
    SETTING_KEYS.APP_NOTIFICATIONS,
    SETTING_KEYS.APP_NOTIFICATIONS_ON_APPROVAL,
    SETTING_KEYS.APP_NOTIFICATIONS_ON_COMPLETE,
  ]),
  memory: new Set<string>([
    SETTING_KEYS.MEMORY_ENABLED,
    SETTING_KEYS.MEMORY_DIRECTORY,
    SETTING_KEYS.MEMORY_CONTEXT_BUDGET_CHARS,
    SETTING_KEYS.MEMORY_SEARCH_DEFAULT_LIMIT,
    SETTING_KEYS.MEMORY_SEARCH_MAX_LIMIT,
  ]),
  hooks: new Set<string>([
    SETTING_KEYS.HOOKS_USER_ENABLED,
    SETTING_KEYS.HOOKS_PROJECT_ENABLED,
    SETTING_KEYS.HOOKS_TRUSTED_PROJECT_ROOTS,
    SETTING_KEYS.HOOKS_INCLUDE_USER_TEXT,
    SETTING_KEYS.HOOKS_INCLUDE_TOOL_ARGUMENTS,
    SETTING_KEYS.HOOKS_INCLUDE_TOOL_RESULTS,
    SETTING_KEYS.HOOKS_TIMEOUT_MS,
  ]),
} as const;

export const CATEGORY_ORDER: Array<keyof typeof CATEGORY_KEYS> = ['models', 'safety', 'tools', 'ui', 'memory', 'hooks'];
